id: IFBC723F2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T19:17:51+00:00'
last_modified: '2022-06-08T06:53:01.229490+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016273
  title: བཀྲ་ཤིས་སྒོ་མང་གི་མཁས་དབང་དག་གི་གསུང་དེང་དུས་དཔེ་རྒྱུན་ཤིན་ཏུ་དཀོན་པ་རྣམས་ལས་འདིར་གང་བྱུང་ཞིག་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    17AA:
      image_group_id: I00JW501152
      title: ''
      total_pages: 622
      order: 1
      base_file: 17AA.txt
    D502:
      image_group_id: I00JW501153
      title: ''
      total_pages: 600
      order: 2
      base_file: D502.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
